apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: toh-lagom-java
  region: ${AWS_REGION}
nodeGroups:
  - name: workers
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 3
    labels:
      app: toh-lagom-java
      actorSystemName: toh-lagom-java
    ssh:
      allow: true
      #publicKeyPath: ... # will use ~/.ssh/id_rsa.pub as the default ssh key
availabilityZones:
  - ${AWS_REGION}a
  - ${AWS_REGION}f
